name: Build information
description: Print branch and Commit hash
runs:
  using: composite
  steps:
    - run: echo "Branch name - $GITHUB_REF_NAME"
      shell: bash
    - run: echo "Commit hash - $GITHUB_SHA"
      shell: bash
