on:
  push:

jobs:
  build-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build info action
        uses: ./.github/actions/build-info
