name: Parallel Checks
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Linting checking
        run: echo "Linting checking"
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Unit testing
        run: echo "Unit testing.."
  package:
    needs: [lint, unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Packaging all
        run : echo "Pacaking done"
