name: Prove the secret reaches a run
on:
  push:
jobs:
  secret-prove:
    runs-on: ubuntu-latest
    steps:
      - name: Prove secrets
        env:
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
        run: |
           if [ -n "$APP_TOKEN" ]; then
              echo "Token is available to this steps"
            fi
